default_connection_name = "default"

[connections]
[connections.default]
account = "$SNOWFLAKE_ACCOUNT"
user = "$SNOWFLAKE_USER"
password = "$SNOWFLAKE_PASSWORD"
warehouse = "$SNOWFLAKE_WAREHOUSE"

[connections.litecoin]

account = "${SNOWFLAKE_ACCOUNT}"
user = "${SNOWFLAKE_USER}"
password = "${SNOWFLAKE_PASSWORD}"
warehouse = "${SNOWFLAKE_WAREHOUSE}"
database = "${SNOWFLAKE_DATABASE}"
schema = "${SNOWFLAKE_SCHEMA}"

[cli.logs]
save_logs = true
level = "info"
path = "/root/UMBC-DATA606-Capstone/logs"

